name: expense_tracker
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_speed_dial: ^7.0.0
  url_launcher: ^6.1.7
  loader_overlay: ^5.0.0
  syncfusion_flutter_charts: ^28.2.12
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
